# Generated by Django 6.0.2 on 2026-02-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=40)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('activado', 'Activado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='rental.vehicles')),
            ],
        ),
    ]
