# Generated by Django 6.0.2 on 2026-02-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Rental',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
